About contactme page
Sonikak004/portfolio-setup pull request #2
Opened 2022-12-03 18:02 UTC by Sonikak004

created about me page, my recent works and contact me page using css and html

2022-12-03 18:42 UTC, ichala requested changes
Hi @Sonikak004 
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No linter errors  ✔️ 
- Good design ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑  Check The Comments Below_**





## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 18:42 UTC, ichala commented on index.html
> +                <div class="works_header-text">MY Recent Works</div>
- [ ] the section title 'My Recent Works' should be a `<hx>` tag instead of normal divs, kindly fix it to be semantically correct 🙏

2022-12-03 18:42 UTC, ichala commented on index.html
> +                        </ul>
- [ ] kindly reduce the padding for your technologies list and align the text to the center to match the Figma design 🙏 

your design: 

![image](https://user-images.githubusercontent.com/89282221/205456408-c14e1775-0bb6-465b-88b6-9d7d6b4382e8.png)

Figma design : 

![image](https://user-images.githubusercontent.com/89282221/205456420-5432386e-a7f8-42a6-a414-1137115d2040.png)

2022-12-03 18:42 UTC, ichala commented on index.html
> +                        </button>
- [ ] kindly remove the small empty space between the card and the see project button to match the Figma design

![image](https://user-images.githubusercontent.com/89282221/205456461-b2ffcc2a-5439-4ead-960b-42c38641c278.png)

2022-12-03 18:42 UTC, ichala commented on index.html
> +                       <title class="cardt" >Profesional Art Printing Data</title>
- [ ] to be semantically correct the card titles should use `<hx>` tags instead of <title> tag , kindly fix it

2022-12-03 18:42 UTC, ichala commented on index.html
> +                             <a class="ltext1" href="#"> See Project </a>
- [ ] Kindly align the text of your `See Project` buttons and add the button interaction styles since its part of the requirements

![image](https://user-images.githubusercontent.com/89282221/205456555-89dc670f-6250-4c2e-b7c3-2e49a50bcb0d.png)

2022-12-03 18:42 UTC, ichala commented on index.html
> +                    <div class="titr">Language</div>
- [ ] to match the figma design, kindly add the missing background image for the about me section 

![image](https://user-images.githubusercontent.com/89282221/205456578-1a48cdb9-1a21-4a59-ae67-8f22ddf442ea.png)

2022-12-03 18:42 UTC, ichala commented on index.html
> +            </div>
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") should be wrapped in a `<ul>`, and each of them in a `<li>`, kindly fix it 🙏

2022-12-03 18:42 UTC, ichala commented on index.html
> +                </ul>
- [ ] to match the figma design, The technology in each category should be aligned center , kindly fix it

your design : 
![image](https://user-images.githubusercontent.com/89282221/205456689-0116f16a-49c9-489d-8382-b4afe9f52d0f.png)

figma design : 
![image](https://user-images.githubusercontent.com/89282221/205456707-5ac92e59-43ef-4dd3-8f9d-3cf6f47f2ee5.png)

2022-12-03 18:47 UTC, Sonikak004 commented on index.html
> +                <div class="works_header-text">MY Recent Works</div>
done

2022-12-03 18:49 UTC, Sonikak004 commented on index.html
> +                        </ul>
done

2022-12-03 22:46 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Sonikak004 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 22:46 UTC, anagudelogu commented on index.html
> +        <h1>My Recent Works</h1>
- [ ] Great job applying the last reviewer's suggestion! 💯 However, please avoid using more than one `<h1>` tag per page. This tag is reserved for the most relevant content of the page, so by convention, it's a good practice to have just one. Instead, you could use another one from `<h2>` to `<h6>`. Please consider fixing this one! 🤓 🛠️

2022-12-03 22:46 UTC, anagudelogu commented on index.html
> +            <li><img src="tag4.png" alt="" /></li>
- [ ] While you did a good job working on the reviewer suggestion, there's a new bug with the technology badges, they are not showing anymore, just the bootstrap one:

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/205464829-97521871-f5e7-4221-8a1d-8293d9541005.png) | ![image](https://user-images.githubusercontent.com/77069011/205464706-c5cfa64c-ee18-4109-a083-f03398fd8fd7.png) |

Please consider fixing this too! 🤓 🛠️

2022-12-03 22:46 UTC, anagudelogu commented on index.html
> +        <h1>Professional Art Printing Data</h1>
- [ ] Great job applying the last reviewer's suggestion! 💯 However, please avoid using more than one `<h1>` tag per page. This tag is reserved for the most relevant content of the page, so by convention, it's a good practice to have just one. Instead, you could use another one from `<h2>` to `<h6>`. Please consider fixing this one! 🤓 🛠️

2022-12-03 22:46 UTC, anagudelogu commented on index.html
> +        </p>
- [ ] Great job working on the previous reviewer's suggestion for the background image of this section! 💯 However, you added the wrong image here. Please try to stick as much as possible with the Figma design! 🎨 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/205465009-0449f5b6-c49a-4522-acba-8cd678d6de71.png) | ![image](https://user-images.githubusercontent.com/77069011/205465001-49d48b53-0294-4614-ac96-0990d5a1c807.png) |

Please consider fixing this one! 🤓 🛠️

2022-12-03 22:46 UTC, anagudelogu commented on index.html
> +        <ul>
- [ ] As the previous reviewer requested, It would be better if you can use an `<ul>` for this part of your portfolio. This is because you're listing skills: Languages, Frameworks, and Skills.

Please consider refactoring your code to end up with something like this:

```HTML
<ul>
  <li>
    <h3> Languages </h3>
    <ul>
      <li> JavaScript </li>
      <li> HTML </li>
      <li> CSS </li>
    </ul>
  <li>
  <li>
    <h3> Frameworks </h3>
  <li>
  <li>
    <h3> Skills </h3>
  <li>
</ul>

```

Please consider implementing this change! 🤓 🛠️

2022-12-03 23:51 UTC, Debas-31 requested changes
> ## Hi @Sonikak004  :wave:, 
# Status: Require Change :recycle:
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"/>


 ## Highlights
- GitHub flow :heavy_check_mark: 
- Commit message :heavy_check_mark:
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 23:51 UTC, Debas-31 commented on index.html
> +                            <img src="icon5.png" alt="Medium icon"></a>
- [ ]  While you did a good job working on the reviewer's suggestion, there's a new bug with the entire design, and they are not showing anymore, even in your previous work review implementation. Kindly fix :wrench: the bug introduced in your design.

***Your design***

![Screenshot from 2022-12-04 02-37-36](https://user-images.githubusercontent.com/65129228/205466988-fde2199d-1dc6-471f-a308-97d76ef209a3.png)

2022-12-07 09:51 UTC, christianbiring1 requested changes
Hi @Sonikak004 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/206145418-2bcd744b-8793-4cde-a8f8-97f69a036002.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 
- [ ] Good looking UI :art: :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] using the same font-weight as the original figma template on all your elelemts.
`HInt: To get an element style in Figma, just click that element and you will see the styles of it popup on the right side`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 09:51 UTC, christianbiring1 commented on index.html
> +                        <title class="cardt" >Profesional Art Printing Data</title>
- [ ] Kindly you may consider giving this image the right path.
`hint: To make your repo well organized, Kindly you may consider putting all your images in a directory called images or assets`
![image](https://user-images.githubusercontent.com/97100091/206144769-5386ae06-2310-4c3e-91d2-46a74713eb18.png)

2022-12-08 11:57 UTC, Alfredbis29 requested changes
Hi @Sonikak004 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
:white_check_mark: Great use of GitHub flow. :100:
:white_check_mark: Your project is documented professionally. 
:white_check_mark: Descriptive PR title, summary and commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Check under the review
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 11:57 UTC, Alfredbis29 commented on index.html
> +                don't hestiate to contact me.</p>
- [ ] I can see that you did some changes but you still have something to improve but you are almost there, as we are imitating the Figma design and if we compare your design to the Figma one they are not really similar, kindly fix this your paragraph is not really readable :wink: 
your design :point_down: 
![Screenshot from 2022-12-08 13-31-08](https://user-images.githubusercontent.com/88894525/206437725-d8f2816d-cc33-4b2e-a0df-8e8ddf4b4433.png)

figma design 
![Screenshot from 2022-12-08 13-33-15](https://user-images.githubusercontent.com/88894525/206437862-e61a3826-45c7-446f-ae02-e3e01314840e.png)

2022-12-08 11:57 UTC, Alfredbis29 commented on index.html
> +                <section class="About-myself">
- [ OPTIONAL] I made this as optional because it was required in the previous review but not yet address , Your about section misses the icon below, as we can all see that on the Figma design we have the icon down the paragraph but on your project is invisible, kindly fix this so that your website will look more attractive and recruiters can reach you out :wink:  

your design
![Screenshot from 2022-12-08 13-36-04](https://user-images.githubusercontent.com/88894525/206438704-a741c56f-0745-49a1-a1d6-642bd5b47b9e.png)

Figma Design
![Screenshot from 2022-12-08 13-35-28](https://user-images.githubusercontent.com/88894525/206438771-a4f27d1c-57a5-46dd-a7b3-911cce782ba1.png)

2022-12-08 11:57 UTC, Alfredbis29 commented on index.html
> +                    <textarea class="form-text2" name="comment" placeholder="Enter text here" maxlength="500"></textarea>
- [ ]  I noticed that your font-weight is so bold than Figma one when typing in the text area can you please take care of this :point_down: 

![Screenshot from 2022-12-08 13-30-36](https://user-images.githubusercontent.com/88894525/206439363-acae8a75-93ae-4a52-9636-a9db74a70bd5.png)

Figma design
![Screenshot from 2022-12-08 13-33-54](https://user-images.githubusercontent.com/88894525/206439477-2a856f42-9ced-4315-b31e-55cd95a4a136.png)

2022-12-08 12:25 UTC, Sonikak004 commented on index.html
> +                don't hestiate to contact me.</p>
hi, do you want me to fix the paragraph or the image?

2022-12-08 14:37 UTC, Debas-31 requested changes
> ## Hi @Sonikak004  :wave:, 
# Status: Require Change :recycle:
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/WTdg5GBR45X6NbxqJK/giphy.gif"/>

 ## Highlights
- GitHub flow :white_check_mark: 
- Project is documented professionally :white_check_mark: 
- Descriptive PR title, summary, and commit messages :white_check_mark:
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 14:37 UTC, Debas-31 commented on index.html
> +                <section class="About-myself">
- [ ] Great job on the implementation of the code reviewer suggestion :+1:

2022-12-08 14:37 UTC, Debas-31 commented on index.html
> +                don't hestiate to contact me.</p>
- [ ]  While you did a good job working on the reviewer's suggestion, there's a new bug within the design, and they are not showing anymore, even in your previous work review implementation. Kindly fix :wrench: the bug introduced in your design.

***Your design***

![Screenshot from 2022-12-08 17-17-07](https://user-images.githubusercontent.com/65129228/206470829-851061d9-0ade-4e9e-95d6-552b9d424790.png)

2022-12-08 16:48 UTC, PinkMoon25 approved these changes
Hi @Sonikak004 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
professional readme :heavy_check_mark: 
Linters checks :heavy_check_mark: 
follows figma design :heavy_check_mark: 

## Optional suggestions

[OPTIONAL] Since it is just one requirement, I am approving the project but Please Implement the buttons hover functionality as it is provided in the figma template: 
![image](https://user-images.githubusercontent.com/97521557/206512458-0ad1c380-2d25-495d-9667-570ee8ff6957.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 09:02 UTC, merged